
title: Santa Monica Cultural Affairs

permalink: pretty

exclude:
  - CNAME
  - README

defaults:
  - scope:
      path: ""
    values:
      layout: default

collections:
  uploads:
    title: Uploads
    output: true

# For cache busting
version: 0.0.0
