---
title: Santa Monica Cultural Affairs

description: Santa Monica Cultural Affairs (SMCA) funds local artists and organizations,
  stewards the city’s public art collection, and produces events large and small.

image: https://static-artsamo.digitalservice.la/uploads/artsamo.jpg

permalink: pretty

collections:
  events:
    title: Events
    output: true
    permalink: "/:path/"

defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: events
  values:
    layout: event

exclude:
- CNAME
- README
- Gemfile
- Gemfile.lock
- _node

version: 0.0.1

