---
title: Santa Monica Cultural Affairs
timezone: UTC
collections:
  events:
    title: Events
    output: true
    permalink: "/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: events
  values:
    layout: default
description: 'Santa Monica Cultural Affairs (SMCA) funds local artists and organizations,
  stewards the city’s public art collection, and produces events large and small. '
image: https://beta-artsamo.digitalservice.lahttps://static-artsamo.digitalservice.la/uploads/artsamo.jpg
permalink: pretty
exclude:
- CNAME
- README
- Gemfile
- Gemfile.lock
- _node
version: 0.0.0
